language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t burakguneri/docker-react -f Dockerfile.dev .

script:
  - docker -e CI=true run burakguneri/docker-react npm run test -- --coverage